addSbtPlugin("com.vmunier"               % "sbt-web-scalajs"           % "1.2.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"               % "1.10.0")
addSbtPlugin("io.spray"                  % "sbt-revolver"              % "0.9.1")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"              % "1.1.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager"       % "1.9.9")
addSbtPlugin("com.typesafe.sbt"          % "sbt-twirl"                 % "1.5.1")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject"  % "1.2.0")
