addSbtPlugin("com.vmunier"               % "sbt-web-scalajs"           % "1.3.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"               % "1.19.0")
addSbtPlugin("io.spray"                  % "sbt-revolver"              % "0.10.0")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"              % "2.3.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager"       % "1.11.4")
addSbtPlugin("org.playframework.twirl"   % "sbt-twirl"                 % "2.0.7")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject"  % "1.3.2")
